name: 🧪 Portfolio Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  markdown-lint:
    name: 📄 Markdown Lint
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Checkout repo
      uses: actions/checkout@v3

    - name: 📦 Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: 📥 Install markdownlint-cli
      run: npm install -g markdownlint-cli

    - name: ✅ Run markdownlint
      run: markdownlint '**/*.md'

